version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ../:/usr/src/app
    command: sh -c "npm install && npm run dev"
    # command: sh -c "npm install && npm run build && npm run start"
    ports:
      - "3000:3000"

  redis:
    image: "redis:5.0.14"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
